# This workflow builds a Java project with Gradle, caches dependencies, and submits dependency information.
# It improves the build speed by caching Gradle dependencies and uses Gradle Wrapper for builds.
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Validate cache restoration
      run: if [ -d ~/.gradle/caches ]; then echo "Cache found"; else echo "Cache not found"; fi

    - name: Run Gradle build
      run: gradle build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Validate cache restoration
      run: if [ -d ~/.gradle/caches ]; then echo "Cache found"; else echo "Cache not found"; fi

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
